### ISSUE TITLE
上田さん | 管理者のCRUD

### ISSUE THREAD

**Issue by yoyoyoheyheyhey** [dai-gi/customer-management-app#16]
自分（ログインユーザー自身）は消せないようにする

**Comment by dai-gi** [comment]
管理者のみが他のアカウントの削除を行えるように実装しました。
管理者自身、ログイン中のアカウント自身も削除できないようになっています。
あと、下記を画面に追加しました。
- サイドバーにログイン中のアカウント名を表示
- アカウント一覧画面にアカウント登録ボタンを追加（管理者のみ表示）
<br />
<br />
<img width="318" alt="スクリーンショット 2023-12-14 18 48 18" src="https://github.com/dai-gi/customer-management-app/assets/59759668/016634c2-96d4-48c1-9e82-69a12ae6a61f">
<br />
<br />
<img width="1664" alt="スクリーンショット 2023-12-14 19 11 07" src="https://github.com/dai-gi/customer-management-app/assets/59759668/47890030-0151-4e4b-a2b8-fe6a343d4248">

**Comment by yoyoyoheyheyhey** [comment]
素晴らしいです！！
