### ISSUE TITLE
上田さん | ユーザーとメニューの削除は論理削除にする

### ISSUE THREAD

**Issue by yoyoyoheyheyhey** [dai-gi/customer-management-app#19]
例えば来店履歴のあるメニューを消そうとすると、snapshotがFKをもっているのでエラーになってしまう

**Comment by dai-gi** [comment]
管理者がそれぞれを誤って削除してしま場合を想定して、管理者、顧客、メニューを論理削除できるようにしました。
下記を追加/変更を行っています。（管理者のみ表示されるようになっています）
- サイドバーにアーカイブリンク追加
- アーカイブページ作成
- アカウント、顧客、メニューそれぞれの削除ボタンを変更（各詳細画面の削除ボタンをアーカイブボタンに変更しています）
<br />
<br />
<img width="1666" alt="スクリーンショット 2023-12-14 19 00 30" src="https://github.com/dai-gi/customer-management-app/assets/59759668/ecac6b38-dacb-4662-9c81-b4a67558f63f">
<br />
<br />
<img width="1652" alt="スクリーンショット 2023-12-14 19 02 31" src="https://github.com/dai-gi/customer-management-app/assets/59759668/a72aa5b8-ae94-4526-9791-e2f2dc7919cc">
<br />
<img width="1665" alt="スクリーンショット 2023-12-14 19 02 56" src="https://github.com/dai-gi/customer-management-app/assets/59759668/b5de9f41-ab62-469f-912f-89bb50f37eb3">

**Comment by yoyoyoheyheyhey** [comment]
ありがとうございます！
