### ISSUE TITLE
上田さん | 顧客ごとの画像一覧画面を作成

### ISSUE THREAD

**Issue by yoyoyoheyheyhey** [dai-gi/customer-management-app#21]
customer has_many 画像

頭の状態とかを写真とって保存するユースケース

**Comment by dai-gi** [comment]
顧客画面一覧を作成しました。

画像は500x500で保存される感じになっています。
<br>
<br>
<img width="1661" alt="スクリーンショット 2023-12-16 20 33 33" src="https://github.com/dai-gi/customer-management-app/assets/59759668/5b1daeab-2844-468b-87e1-6a883658b145">
<br>
<br>
<img width="1658" alt="スクリーンショット 2023-12-16 20 34 03" src="https://github.com/dai-gi/customer-management-app/assets/59759668/cdbfe7af-810a-4540-a713-d74d4c760040">
<br>
<br>
<img width="1663" alt="スクリーンショット 2023-12-16 20 34 19" src="https://github.com/dai-gi/customer-management-app/assets/59759668/6cfc5126-2fa0-4a46-bd07-a171c439a04a">

**Comment by yoyoyoheyheyhey** [comment]
@dai-gi ありがとうございます！
